### ISSUE TITLE
Use a small Golang Web Application instead of a dedicated Web Server

### ISSUE THREAD

**Issue by hypebeast** [vollstock/Tooloop-OS#1]
Maybe it's a better idea to write a small Web-App with Golang in order to implement the Tooloop OS Config Tool/Management Server.

With a Golang Web-App there is no need for an extra Web Server. This would make the overall system architecture simpler.

**Comment by vollstock** [comment]
I agree, I would't want a webserver running on the machine. The idea is to have a small application/daemon running, that offers a web interface. I had a look at [Mongoose](https://github.com/cesanta/mongoose/). I know nothing about Go. What's the advantage over a C/C++ app?

My goal for the config tool is to be as lightweight as possible. I think performance is not the primary criteria here. The web interface can be very simple.

Under the hood, I have this idea of using [Augeas](http://augeas.net/index.html). This has the benefit that we can manipulate various system settings via the command line (and thus the post install scripts in the installer), as well as using Augeas as library to do the same from within the config tool. Augeas has a C API but comes with [plenty of language bindings ](http://augeas.net/faq.html#using-augeas) including Go.

**Comment by vollstock** [comment]
For your interest, here's a simple example of a [restful server, driven by mongoose](https://github.com/cesanta/mongoose/blob/master/examples/restful_server/restful_server.c).

**Comment by hypebeast** [comment]
> I agree, I would't want a webserver running on the machine. The idea is to have a small application/daemon running, that offers a web interface. I had a look at Mongoose. I know nothing about Go. What's the advantage over a C/C++ app?

I got it. I thought that Mongoose is a fully featured web server, but it's a web server framework for C/C++. That makes more sense. But I think it would be a better idea to use something like Go for writing the web interface, because Mongoose is quite low-level and it's not so straight forward to write a web service as compared to Go. I just think that it would be easier and faster to use a more 'high-level' language with build-in support for web-server applications.

> My goal for the config tool is to be as lightweight as possible. I think performance is not the primary criteria here. The web interface can be very simple.

The overhead of Go compared to Mongoose would be just marginal and we don't need to support embedded platforms. Therefore, it would be ok if the web services consumes some more megabytes of RAM (imo). I think you can even use Python or something like that and it would be still fine.

> Under the hood, I have this idea of using Augeas. This has the benefit that we can manipulate various system settings via the command line (and thus the post install scripts in the installer), as well as using Augeas as library to do the same from within the config tool. Augeas has a C API but comes with plenty of language bindings including Go.

Augeas sounds like a good idea to manage different application configs :+1:

**Comment by vollstock** [comment]
I Kind of believe that although embedded devices are not the primary scope, it might be a good idea to treat Tooloop OS as such anyway. 

- I don't want the server to cause any hiccup at all while the presentation is running
- I want the service to be fast. Admitted, the most time will go into network traffic and has to be tackled by a very thoughtful and lightweight web front end but anyway. It's annoying, to administrate boxes on the other side of the world (you know that;-))
- most important, I see no reason why Tooloop OS might not get a fork, based on Raspbian for the Raspberry Pi one day

After fiddling with some code for a while and thinking some more, I still believe, mongoose is a good choice. I have the web front end mostly done and attached to some ugly server implementation. Check it out, the binary is in the Tooloop OS repo. Right now, it will host a service on port 8000 by default and does pretty much nothing except providing some server side variables and serving static content.

However, if you feel like giving the Go server or a Python service a try, I'm more than happy to see what you're up to.

**Comment by vollstock** [comment]
will close this as there's the [Tooloop Settings Server](https://github.com/vollstock/Tooloop-Settings-Server) now :-)
