### ISSUE TITLE
Check out Ubuntu 18.04 LTS

### ISSUE THREAD

**Issue by vollstock** [vollstock/Tooloop-OS#15]
What impact does it have?
What’s different?
What breaks?
What has improved?

**Comment by vollstock** [comment]
Awesome. However if you really plan to use it for production, I would recommend against it and stick with 16.04.

There is nothing bad about it and t will be supported until 2021.
This issue is more of a general future research task :-)

Having said this, go ahead, play, test, have fun :-) Any contribution is highly welcome!!

**Comment by gabriel-lucas** [comment]
Hi Daniel,

Yesterday I installed 5 pcs. (1x Ubuntu server 18.04, 2x Ubuntu server 16.04, 2x Ubuntu desktop 16.04) and today I will play around with them.

My first impressions are really nice, congratulations. I was searching for a project just like this.
I have been looking around for some time but the options I was finding were not adequate for one reason or the other. I will try to contribute to the project.

 I can respond to one of the questions you ask.  What breaks?   In ubuntu 18.04 server, the openbox option ->  "open terminal" and "open clock" don´t work.

**Comment by vollstock** [comment]
hm, that’s funny. Those are simply calls to
    /usr/bin/xterm
    /usr/bin/xclock

Maybe those are not installed under 18.04.
Anyway if it’s just minor things like that and the overall system still works, I should probably start a new branch soon.

**Comment by vollstock** [comment]
I have moved the appcenter branch to 18.04.
So once this is merged, the version bump will come with it :-)
