### ISSUE TITLE
OpenFrameworks error on install

### ISSUE THREAD

**Issue by DigitalFlodur** [vollstock/Tooloop-OS#18]
Installing on VM, I got this error. I have attached screenshots of the terminal logs.
![screen shot 2018-07-14 at 2 55 17 pm](https://user-images.githubusercontent.com/5292399/42728736-4f91de58-8776-11e8-8165-38ceec20440e.png)
![screen shot 2018-07-14 at 2 55 27 pm](https://user-images.githubusercontent.com/5292399/42728735-4f7b5e76-8776-11e8-8efb-45ebf2755b0d.png)
![screen shot 2018-07-14 at 2 56 00 pm](https://user-images.githubusercontent.com/5292399/42728734-4f634520-8776-11e8-9a90-05c1accb421f.png)
![screen shot 2018-07-14 at 2 56 40 pm](https://user-images.githubusercontent.com/5292399/42728733-4f4bc3b4-8776-11e8-8ab2-72b1ac6a7eee.png)

**Comment by jmarsico** [comment]
it looks like oF has some certificate issues. you can modify the `/opt/tooloop/scripts/tooloop-install=optional-stuff` script by adding the `--no-check-certificate` to the end of this line:

`wget http://openframeworks.cc/versions/v${OF_VERSION}/of_v${OF_VERSION}_linux64_release.tar.gz`

**Comment by jmarsico** [comment]
pull request: https://github.com/vollstock/Tooloop-OS/pull/20
