### ISSUE TITLE
Xterm can't open display

### ISSUE THREAD

**Issue by Craigson** [vollstock/Tooloop-OS#27]
I have a fresh install of Tooloop on Ubuntu 16.04.

The desktop does not launch on boot.  If I manually try running a script, for example `./tooloop-terminal` I get the following error: `~/Tooloop-OS/files/scripts$ /usr/bin/xterm: Xt error: Can't open display`

I can manually start open box using `sudo startx` the launches on the display, but it is not the Tooloop OS.

**Comment by vollstock** [comment]
I believe, your problem has the same origin as in #28 .
Your username has to be `tooloop` exactly.

**Comment by Craigson** [comment]
That makes sense, thanks Daniel.  I installed the OS on top of an existing ubuntu server instance, so that makes sense.

**Comment by Craigson** [comment]
Got it up and running and it looks great. Reinstalling ubuntu on hardware usually takes 10mins, almost easier than setting up the VM!!
