### ISSUE TITLE
Terminal aliases not set by default

### ISSUE THREAD

**Issue by Craigson** [vollstock/Tooloop-OS#28]
Upon first boot the terminal aliases are not being found.
If I run `tooloop-settings` it yields the error `tooloop-settings: command not found`

**Comment by Craigson** [comment]
Are the aliases predicated on the use being `tooloop-box`?

**Comment by vollstock** [comment]
The system relies heavily on the username to be `tooloop`.

Config files, user rights, file ownership of certain folders, auto login,…
If you named the user differently during installation, nothing will work.

The hostname (= name of the box) and the user password can be whatever you like, though.
